### ISSUE TITLE
Incorrect JSON response on Controller/Plugins

### ISSUE THREAD

**Issue by wouterlucas** [WebPlatformForEmbedded/WPEFramework#1]
Using an open source build, so probably some of the normally present events/systems/components are missing which results into an incorrect JSON request on /Controller/Plugins.

Request made:
```
GET http://192.168.11.102/Service/Controller/Plugins
Accept: */*
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9,nl;q=0.8
Connection: keep-alive
DNT: 1
Host: 192.168.11.102
Referer: http://192.168.11.102/Service/Controller/UI?ip=192.168.11.102&port=80
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36
```

Response:
```
200 OK
Access-Control-Allow-Origin: *
Cache-Control: no-cache, private, no-store, must-revalidate, max-stale=0, post-check=0, pre-check=0
Content-Length: 4960
Content-Type: application/json
```

Response body [wpeframework-controller-plugins.txt](https://github.com/WebPlatformForEmbedded/WPEFramework/files/2041977/wpeframework-controller-plugins.txt)

Has error in JSON:
```
Error: Parse error on line 2:
...:{    "subsystems":,    "resumes":[  
----------------------^
Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got ','
```

Configuration of WPEFramework also attached here 
[WPEFramework.zip](https://github.com/WebPlatformForEmbedded/WPEFramework/files/2041979/WPEFramework.zip)

**Comment by pwielders** [comment]
Bram looks like a CMAKE issue. If the list is empty, place null, or leave out the full entry.

**Comment by bramoosterhuis** [comment]
Is this still an issue? I can't reproduce it...

**Comment by wouterlucas** [comment]
I don't think so, also this should resolve it in the long term: https://github.com/WebPlatformForEmbedded/WPEFramework/pull/28

Will close this.
