### ISSUE TITLE
reload or new url api json

### ISSUE THREAD

**Issue by admindotnu** [WebPlatformForEmbedded/WPEFramework#110]
Can someone give us a start how to reload an url or set a new url using the api.

Looking at the docx file, absolute still no idea...

Thank you !

**Comment by admindotnu** [comment]
With the correct json call, i will be very fine !

**Comment by admindotnu** [comment]
Nobody ?

**Comment by wouterlucas** [comment]
Hi @admindotnu 

You may want to have a look at the WebKitBrowser plugin documentation, which can be found here:

From that doc:
```
POST /Service/WebKitBrowser/URL
{"url":"http://www.admin.nu"}
```

Should do the trick (of course needs content-length and content-type, but you get the idea).

This will change in the near future to be a JSON RPC message, where the method is `WebKitBrowser.1.seturl` and the url json goes in the params (for more info see https://www.jsonrpc.org/specification)

**Comment by admindotnu** [comment]
Hi Wouterlucas,

Thank you, for pointing me the correct doc !
