### ISSUE TITLE
Crash in WPEFramework::ProxyStub::UnknownProxyType<OCDM::IAccessorOCDM>::Release

### ISSUE THREAD

**Issue by GlebNovodranPE** [WebPlatformForEmbedded/WPEFramework#113]
Sometimes we observe a SIGSEGV upon an application exit.
The crash happens in
`WPEFramework::ProxyStub::UnknownProxyType<OCDM::IAccessorOCDM>::Release`
called from `media::AccessorOCDM::~AccessorOCDM`.
Here is the [stack trace](https://github.com/WebPlatformForEmbedded/WPEFramework/files/3141410/stack_trace.txt)
The immediate reason of the crash is that the dynamic_cast operation below is performed on a wild memory 

`        
inline ProxyType<CONTEXT>
        GetProxy(
            unsigned int Index) const
        {
			CONTEXT* baseClass = dynamic_cast<CONTEXT*> (m_List[Index]);
            return (ProxyType<CONTEXT>(m_List[Index], baseClass));
        }
`

This happens then in `media::AccessorOCDM::Release` IUnknown reference counter reaches zero and the following code gets executed:

`                    // We have reached "0", signal the other side..
                    Core::ProxyType<RPC::InvokeMessage> message(RPC::Administrator::Instance().Message());
`
At the moment we most recent commit of the version we use is #d4e40417c6
`WPEFramework::RPC::Administrator` seems to be destroyed by this time.

The crash doesn't happen upon every application exit. Something seems to be keeping hold of the reference to AccessorOCDM.

**Comment by GlebNovodranPE** [comment]
Here is a [stack trace](https://github.com/WebPlatformForEmbedded/WPEFramework/files/3147615/stack_trace_all_threads.txt) of all threads.

**Comment by GlebNovodranPE** [comment]
And another [one](https://github.com/WebPlatformForEmbedded/WPEFramework/files/3147637/stacktrace.txt)

**Comment by pawel-stanek-ml** [comment]
Thanks for the very detailed info.
These areas have been heavily changed recently: WPEWebkit switched from using C++ OCDM API to C one, there were many fixes in OCDM and framework (which you seem to have from almost a year ago) layers. Is updating and reevaluating an option here?

**Comment by GlebNovodranPE** [comment]
Thank you, we are planning on a revision update in a few weeks.
I will reopen the issue if the problem reoccur with the updated version.
