### ISSUE TITLE
Error in JSON::Container::Serialize

### ISSUE THREAD

**Issue by bobseamon** [WebPlatformForEmbedded/WPEFramework#147]
in: `WPEFramework::Core::JSON::Container::Serialize`

it converts JsonObject `{"a":"1", "b":[1, 2, 3],"c":{"x":4}}` to string: `"{"a":"1", "b":null,"c":null}"`

Looks like its not serializing values that are objects

**Comment by pwielders** [comment]
Commit: https://github.com/WebPlatformForEmbedded/WPEFramework/commit/07b5fed92dc779b183afa3d542a8882c2fd0c9c8 
will resolve the issue.
