### ISSUE TITLE
Pass the result of the OCDM(i) interface, during decrypt to the Client

### ISSUE THREAD

**Issue by pwielders** [WebPlatformForEmbedded/WPEFramework#19]
Currently the status of the decrypt returned over the OpenCDM Interface is not being forwarded to the client and thus to the users of the OpenCDM.
Suggest to extend the Administration space of the Decrypt Memory Mapped file buffer to carry the status together related to the last decrypt. and forward this to the user of the client.

**Comment by pwielders** [comment]
Two changes have been checked in to fix the issue:
WPEFramework:
https://github.com/WebPlatformForEmbedded/WPEFramework/commit/65e54a7b390aa47c92201251bee8b3b616ac6577

WPEFrameworkPlugins:
https://github.com/WebPlatformForEmbedded/WPEFrameworkPlugins/commit/110b97037bddcf988d8932b1a35fe6b61c80a5a0

Validation needs to be scheduled.

**Comment by goruklu** [comment]
Thanks Pierre, this looks good, I'll test it this week and let you know the result!
