### ISSUE TITLE
OCDM plugin process does not restart automatically after a crash

### ISSUE THREAD

**Issue by goruklu** [WebPlatformForEmbedded/WPEFramework#20]
@pwielders we noticed that if the WPEProcess for the OCDM plugin crashes or dies for some reason, it does not start until we restart the WPEFramework service.

Is it possible to restart OCDM plugin process automatically in case of failure ?

**Comment by pwielders** [comment]
This cab be configured in the Monitor Plugin. The Monitor Plugin can, if it detects that a plugin dies due to the reason "Failure" restart a plugin for a configurable amount of times within a defined period.
