### ISSUE TITLE
Option to disable logging

### ISSUE THREAD

**Issue by woutermeek** [WebPlatformForEmbedded/WPEFramework#8]
[`Here`](https://github.com/WebPlatformForEmbedded/WPEFramework/blob/master/Source/WPEFramework/PluginHost.cpp#L330) you can see that the logging is always turned on.

It should follow the configuration.

**Comment by pwielders** [comment]
I tested it and by default Logging is on but it can be overridden by the config. Checked in in the latest configs that are generated.
